services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    restart: unless-stopped
    volumes:
      # attach the relative directory 'data' to the container's /home/container path
      - ./data:/home/container

  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    environment:
      - PARAMS=tcp -region=us -authtoken=YourAuthTokenHere mc:25565
