services:
  minecraft:
    image: itzg/minecraft-server
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    volumes:
      - ./data:/home/container
    environment:
      EULA: "TRUE"
    restart: unless-stopped
